applications:
  - environments: {}
    sourceRepository:
      apiVersion: jenkins.io/v1
      kind: SourceRepository
      metadata:
        labels:
          gitops.jenkins-x.io/pipeline: namespaces
          owner: rawlingsj
          provider: github
          repository: testapp1
        name: rawlingsj-testapp1
        namespace: jx
      spec:
        httpCloneURL: https://github.com/rawlingsj/testapp1.git
        org: rawlingsj
        provider: https://github.com
        providerKind: github
        providerName: github
        repo: testapp1
        scheduler:
          kind: ""
          name: jx-meta-pipeline
        url: https://github.com/rawlingsj/testapp1
  - environments: {}
    sourceRepository:
      apiVersion: jenkins.io/v1
      kind: SourceRepository
      metadata:
        labels:
          gitops.jenkins-x.io/pipeline: namespaces
          owner: rawlingsj
          provider: github
          repository: testapp2
        name: rawlingsj-testapp2
        namespace: jx
      spec:
        httpCloneURL: https://github.com/rawlingsj/testapp2.git
        org: rawlingsj
        provider: https://github.com
        providerKind: github
        providerName: github
        repo: testapp2
        scheduler:
          kind: ""
          name: jx-meta-pipeline
        url: https://github.com/rawlingsj/testapp2
  - environments: {}
    sourceRepository:
      apiVersion: jenkins.io/v1
      kind: SourceRepository
      metadata:
        labels:
          gitops.jenkins-x.io/pipeline: namespaces
          owner: rawlingsj
          provider: github
          repository: testapp3
        name: rawlingsj-testapp3
        namespace: jx
      spec:
        httpCloneURL: https://github.com/rawlingsj/testapp3.git
        org: rawlingsj
        provider: https://github.com
        providerKind: github
        providerName: github
        repo: testapp3
        scheduler:
          kind: ""
          name: in-repo
        url: https://github.com/rawlingsj/testapp3
  - environments:
      production:
        deployments:
          - name: testapp4
            pods: "1/1"
            url: http://testapp4-jx-production.test.nip.io
            version: 1.0.3
        environment:
          apiVersion: jenkins.io/v1
          kind: Environment
          metadata:
            labels:
              env: production
              gitops.jenkins-x.io/pipeline: namespaces
              team: jx
            name: production
            namespace: jx
          spec:
            kind: Permanent
            label: Production
            namespace: jx-production
            order: 500
            previewGitInfo:
              user: {}
            promotionStrategy: Auto
            source: {}
            teamSettings:
              defaultScheduler:
                kind: ""
                name: ""
          status: {}
      staging:
        deployments:
          - name: testapp4
            pods: "1/1"
            url: http://testapp4-jx-staging.test.nip.io
            version: 1.0.3
        environment:
          apiVersion: jenkins.io/v1
          kind: Environment
          metadata:
            labels:
              env: staging
              gitops.jenkins-x.io/pipeline: namespaces
              team: jx
            name: staging
            namespace: jx
          spec:
            kind: Permanent
            label: Staging
            namespace: jx-staging
            order: 100
            previewGitInfo:
              user: {}
            promotionStrategy: Auto
            source: {}
            teamSettings:
              defaultScheduler:
                kind: ""
                name: ""
          status: {}
    sourceRepository:
      apiVersion: jenkins.io/v1
      kind: SourceRepository
      metadata:
        labels:
          gitops.jenkins-x.io/pipeline: namespaces
          owner: rawlingsj
          provider: github
          repository: testapp4
        name: rawlingsj-testapp4
        namespace: jx
      spec:
        description: Imported application for rawlingsj/testapp4
        httpCloneURL: https://github.com/rawlingsj/testapp4.git
        org: rawlingsj
        provider: https://github.com
        providerKind: github
        providerName: github
        repo: testapp4
        scheduler:
          kind: ""
          name: jx-meta-pipeline
        url: https://github.com/rawlingsj/testapp4
  - environments:
      staging:
        deployments:
          - name: testapp5
            pods: "1/1"
            url: http://testapp5-jx-staging.test.nip.io
            version: 1.0.0
        environment:
          apiVersion: jenkins.io/v1
          kind: Environment
          metadata:
            labels:
              env: staging
              gitops.jenkins-x.io/pipeline: namespaces
              team: jx
            name: staging
            namespace: jx
          spec:
            kind: Permanent
            label: Staging
            namespace: jx-staging
            order: 100
            previewGitInfo:
              user: {}
            promotionStrategy: Auto
            source: {}
            teamSettings:
              defaultScheduler:
                kind: ""
                name: ""
          status: {}
    sourceRepository:
      apiVersion: jenkins.io/v1
      kind: SourceRepository
      metadata:
        labels:
          gitops.jenkins-x.io/pipeline: namespaces
          owner: rawlingsj
          provider: github
          repository: testapp5
        name: rawlingsj-testapp5
        namespace: jx
      spec:
        httpCloneURL: https://github.com/rawlingsj/testapp5.git
        org: rawlingsj
        provider: https://github.com
        providerKind: github
        providerName: github
        repo: testapp5
        scheduler:
          kind: ""
          name: in-repo
        url: https://github.com/rawlingsj/testapp5
  - environments:
      staging:
        deployments:
          - name: testapp6
            pods: "1/1"
            url: http://testapp6-jx-staging.test.nip.io
            version: 1.0.1
        environment:
          apiVersion: jenkins.io/v1
          kind: Environment
          metadata:
            labels:
              env: staging
              gitops.jenkins-x.io/pipeline: namespaces
              team: jx
            name: staging
            namespace: jx
          spec:
            kind: Permanent
            label: Staging
            namespace: jx-staging
            order: 100
            previewGitInfo:
              user: {}
            promotionStrategy: Auto
            source: {}
            teamSettings:
              defaultScheduler:
                kind: ""
                name: ""
          status: {}
    sourceRepository:
      apiVersion: jenkins.io/v1
      kind: SourceRepository
      metadata:
        labels:
          gitops.jenkins-x.io/pipeline: namespaces
          owner: rawlingsj
          provider: github
          repository: testapp6
        name: rawlingsj-testapp6
        namespace: jx
      spec:
        httpCloneURL: https://github.com/rawlingsj/testapp6.git
        org: rawlingsj
        provider: https://github.com
        providerKind: github
        providerName: github
        repo: testapp6
        scheduler:
          kind: ""
          name: in-repo
        url: https://github.com/rawlingsj/testapp6